
[en]
  title = "Clarity"
  LanguageName = "English"
  weight = 1

[pt]
  title = "Claridade" # just for the sake of showing this is possible
  LanguageName = "Português"
  weight = 2

[ja]
  title = "abobon site"
  LanguageName = "日本語"
  weight = 3
