baseURL = 'https://ktaroabobon.github.io/'
languageCode = 'ja'
title = 'My New Hugo Site'

# Global Params
auther = "ktaroabobon"
twitter = "abobon_blog"
largeTwitterCard = true
description = "abobonのブログ"



# Page Params